### PR TITLE
Removed rsync check, added remaining storage check

### PR DESCRIPTION
**Pull request by karlnyr**
### This PR adds and fixes:

- Start of encryption during sequencing to keep the process going and to clear out space
- Limit start of encryption to memory available - undergoing sequencing and encryption should be able to finish

**How to prepare for test**:
- [x] `ssh` to NAS's

### How to test:

- Check if correct percent usage is fetched.

### Expected outcome:

- [x] Percent usage fetched should be same as if checked for /home

### Review:
- [ ] Code approved by
- [x] Tests executed by @karlnyr 
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by karlnyr** [comment]
Testing if the correct percent usage is working correctly on all servers:

Nas-9:

```Command
[hiseq.clinical@nas-9 git]$ PERCENTAGE_STORAGE_USED=$(df -h /home --output=pcent | awk '$0!~/Use/ {print $0}' | sed 's/\s//g' | sed 's/[%]//g')
[hiseq.clinical@nas-9 git]$ echo $PERCENTAGE_STORAGE_USED
15
[hiseq.clinical@nas-9 git]$ df -h /home
Filesystem                     Size  Used Avail Use% Mounted on
/dev/mapper/vg_extend-lv_home   11T  1.5T  8.8T  15% /home
```

Nas-6:

```Command
[hiseq.clinical@nas-6 ~]$ PERCENTAGE_STORAGE_USED=$(df -h /home --output=pcent | awk '$0!~/Use/ {print $0}' | sed 's/\s//g' | sed 's/[%]//g')
[hiseq.clinical@nas-6 ~]$ echo $PERCENTAGE_STORAGE_USED
10
[hiseq.clinical@nas-6 ~]$ df -h /home
Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/VGExtend-lv_home   12T  1.1T   11T  10% /home
```

seq-nas-1

```Command
[hiseq.clinical@seq-nas-1 ~]$ PERCENTAGE_STORAGE_USED=$(df -h /home --output=pcent | awk '$0!~/Use/ {print $0}' | sed 's/\s//g' | sed 's/[%]//g')
[hiseq.clinical@seq-nas-1 ~]$ echo $PERCENTAGE_STORAGE_USED
23
[hiseq.clinical@seq-nas-1 ~]$ df -h /home
Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/cl_seq--nas--1-home   13T  2.8T  9.6T  23% /home
```

clinical-nas-2

```Command
[hiseq.clinical@clinical-nas-2 ~]$ PERCENTAGE_STORAGE_USED=$(df -h /home --output=pcent | awk '$0!~/Use/ {print $0}' | sed 's/\s//g' | sed 's/[%]//g')
[hiseq.clinical@clinical-nas-2 ~]$ echo $PERCENTAGE_STORAGE_USED
29
[hiseq.clinical@clinical-nas-2 ~]$ df -h /home
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        9.9T  2.8T  7.1T  29% /home
```

**Review by Vince-janv — APPROVED** [review]
Nice 🔥 If we ever get to 75% we no longer have any automation though. Is there an easy way to implement a warning being sent to us via mail if this is the case?

**Comment by karlnyr** [comment]
> Nice 🔥 If we ever get to 75% we no longer have any automation though. Is there an easy way to implement a warning being sent to us via mail if this is the case?

Good point. Currently we are sending out a daily warning with "C R I T I C A L" if we go above 50% usage on any NAS. That being said, I think it would be cool to monitor this in trailblazer or cigrid but since we are migrating away from the physical NAS's it might be overkill 🤔

**Comment by karlnyr** [comment]
Tested email which seems to be working properly

**Pull request merged**
