### PR TITLE
Update overviewlog.bash

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds:

- Added nas-6

**How to prepare for test**:
- [ ] `ssh` to ...
- [ ] Install on stage:
`bash servers/resources/SERVER.scilifelab.se/update-[THIS_TOOL]-stage.sh [THIS-BRANCH-NAME]`

### How to test:
-

### Expected outcome:
- [ ]

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by barrystokman — APPROVED** [review]
:+1:

**Comment by henrikstranneheim** [comment]
@barrystokman Would you like to help me deploy?

**Review by eriksjolund — APPROVED** [review]
Looks good.

**Comment by barrystokman** [comment]
Bumped:
image

Deployed:
image

**Comment by henrikstranneheim** [comment]
Thx! Barry!

**Pull request merged**
