### PR TITLE
Feat retrieve

### PR DESCRIPTION
**Pull request by ingkebil**
Some bash kung-fu to retrieve an archive from PDC and at the same time decrypt and untar that archive.

### CODE REVIEW

**Comment by ingkebil** [comment]
callout @Clinical-Genomics/reviewers :)

**Comment by robinandeer** [comment]
very succinct ^^

**Comment by ingkebil** [comment]
Ok to merge?

**Comment by b4ckm4n** [comment]
👍 

PS. Sorry for keeping you hanging guys!

**Comment by wefer** [comment]
:+1:

**Pull request merged**
